const Images = {
    logo: require('../assets/logo.png'),
    userSilhouette: require('../assets/userSilhouette.jpg'),
    editPan: require('../assets/edit.png'),
    dummyImg1: require('../assets/dummyImg1.png'),
    dummyImg2: require('../assets/dummyImg2.png'),
    ic_cross_icon: require('../assets/ic_cross_icon.png'),
    ic_three_dot_icon: require('../assets/ic_three_dot_icon.png'),
    ic_share: require('../assets/ic_share.png'),
    ic_forward: require('../assets/ic_forward.png'),
    ic_page: require('../assets/ic_page.png'),
    ic_Network: require('../assets/ic_Network.png'),
    ic_edit: require('../assets/edit.png'),
    ic_message: require('../assets/ic_message.png'),
    ic_Career: require('../assets/ic_Career.png'),
    ic_Home: require('../assets/Home.png'),
    Home: require('../assets/ic_Home.png'),
    ic_bell: require('../assets/ic_bell.png'),
    image_defaultBanner: require('../assets/defaultBanner.jpg'),
    ic_check_icon: require('../assets/ic_check_icon.png'),
    ic_triangle: require('../assets/ic_triangle.png'),
    ic_see_more: require('../assets/ic_see_more.png'),
    ic_blank_images: require('../assets/ic_blank_images.png'),
    createPageImg: require('../assets/pageCreatedIcon.png'),
    homeTabIcon: require('../assets/home-tab.png'),
    networkTabIcon: require('../assets/network-tab.png'),
    searchTabIcon: require('../assets/search-tab.png'),
    careerTabIcon: require('../assets/career-tab.png'),
    ic_search_icon: require('../assets/ic_nav_search.png'),
    ic_close: require('../assets/ic_close.png'),
    ic_close_white: require('../assets/ic_close_withBg.png'),
    mentalHealthImg: require('../assets/mental-health-poster.png'),
  };
  export default Images;
  