export enum AppScreens {
    Auth = 'Auth',
    Main = 'Main',
    Modal = 'Modal',
  }
  
  export enum AuthScreens {
    Landing = 'Landing',
    Login = 'Login',
    SignUp = 'Landing',
    VerificationCode = 'VerificationCode',
    ForgotPassword = 'ForgotPassword',
    ResetPassword = 'ResetPassword',
    Welcome = 'Welcome',
    InviteFriends = 'InviteFriends',
    SetPasswordScreen = 'SetPasswordScreen',
    ForgotPassCodeScreen = 'ForgotPassCodeScreen',
    PasswordResetSuccessScreen = 'PasswordResetSuccessScreen',
  }
  
  export enum MainScreens {
    HomeFeed = 'HomeFeed',
    Home = 'Home',
    ActivityDetails = 'ActivityDetails',
    UserProfile = 'UserProfile',
    PageDetails = 'PageDetails',
    PageListScreen = 'PageListScreen',
    UsersListScreen = 'UsersListScreen',
    CreatePage = 'CreatePage',
    CreateEvent = 'CreateEvent',
    UserConnections = 'UserConnections',
    MyNetwork = 'MyNetwork',
    MyConnections = 'MyConnections',
    ConnectionRequests = 'ConnectionRequests',
    MentorshipConnectionRequests = 'MentorshipConnectionRequests',
    Network = 'Network',
    NewPost = 'NewPost',
    EditPost = 'EditPost',
    CareerNav = 'CareerNav',
    MessagesNav = 'MessagesNav',
    Messages = 'Messages',
    MessageChat = 'MessageChat',
    NewChat = 'NewChat',
    SettingsStack = 'SettingsStack',
    Languages = 'Languages',
    EditProfileScreen = 'EditProfile',
    ReportOrBlockUser = 'ReportOrBlockUser',
    ReportUser = 'ReportUser',
    Success = 'Success',
    UserStack = 'User',
    NetworkStack = 'NetworkStack',
    MessageStack = "MessageStack",
    SettingsScreen = 'Settings',
    Mentorship = 'Mentorship',
    MyMentorship = 'MyMentorship',
    CreateMentorshipProfile = 'CreateMentorshipProfile',
    AddItem = 'AddItem',
    EditItem = 'EditItem',
    ManageAccount = 'ManageAccount',
    MentorMenteeProfile = 'MentorMenteeProfile',
    ChangePassword = 'ChangePassword',
    NotificationsNav = 'NotificationsNav',
    Notifications = 'Notifications',
    NotificationDetails = 'NotificationDetails',
    Search = 'Search',
    SearchLandingScreen = 'SearchLandingScreen',
    InvitePeople = 'InvitePeople',
    AIAdvisor = 'AIAdvisor',
    AIAdvisorSetGoals = 'AIAdvisorSetGoals',
    AIAdvisorAnswerQuestions = 'AIAdvisorAnswerQuestions',
    AIAdvisorQuestionSteps = 'AIAdvisorQuestionSteps',
    AIAdvisorGenerate = 'AIAdvisorGenerate',
    Welcome = 'Welcome',
    Mentors= 'Mentors',
    BecomeMentorMentee = 'BecomeMentorMentee',
    BlockUserScreen = 'BlockUserScreen'
  }
  